# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d77639b0f524f6abb607bc2ddc64eae3c0a7c7fbcfa92ede21e4770c8c1e5526955dd81e224cb69a2cf12f5cea35f7805a20c12d74d0a9e21036d0e4aa54bea7

test:
  secret_key_base: f0821ddd613434dfd8e605d6ccf153274a85670f7af61d47c7983a21e8537f64ecda1590919a9639db804d76a7890a8cf2ef0600292234cef2d748f419bc2b77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
